---
framework: jest
tier: small
postMerge: 
  pattern: 
    - "./shared/test/*.js"
preMerge:
  pattern:
    - "./shared/test/*.js"
preRun:
     command:
        - yarn install
        - |
          echo "deb http://download.rethinkdb.com/apt jessie main" | sudo tee /etc/apt/sources.list.d/rethinkdb.list
          wget -qO- http://download.rethinkdb.com/apt/pubkey.gpg | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install rethinkdb=2.3.5~0jessie
          rethinkdb --bind all
        - |
          cp now-secrets.example.json now-secrets.json
          yarn run build:web
        - yarn run build:api
        - yarn run start:api:test
        - yarn run dev:web
postRun:
     command:
        - yarn --version
version: 2.1

